name: GitHub Actions Demo

on:
  push:
    branches: 'main'
    paths-ignore: '.github/**'
  pull_request:
    branches: 'main'
  schedule:
    - cron: 15 6 * * SUN
  workflow_dispatch:
    inputs:
      environment:
        description: Environment to deploy to
        type: environment
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Output event trigger
        run: |
          echo "${{ github.event_name }} triggered this job"
      - name: Output branch name
        run: |
          echo "${{ github.ref }} is the name of the branch"
      - uses: actions/checkout@v6
      - name: List all files
        run: |
          echo "The repository contains the files:"
          tree
  Test:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch'
    environment: Test
    steps:
      - name: Testing
        run: |
          echo "Testing..."
        
  Load-Test:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch'
    environment: Load-Test
    steps:
      - name: Testing
        run: |
          echo "Testing..."
          sleep 15
          
  Production:
    runs-on: ubuntu-latest
    needs: [Test, Load-Test]
    if: github.event.inputs.environment == 'Production'
    environment:
      name: Production
      url: https://writeabout.net
    steps:
      - name: Deployment stage 1
        run: |
          echo "Step 1 deploying..."
          sleep 10
      - name: Deployment stage 2
        run: |
          echo "Step 2 deploying..."
          sleep 10
      - name: Deployment stage 3
        run: |
          echo "Step 3 deploying..."
          sleep 10
      - name: Deployment stage 4
        run: |
          echo "Step 4 deploying..."
          sleep 10
      - name: Deployment stage 5
        run: |
          echo "Step 5 deploying..."
          sleep 10
