name: Reuse other workflow

on:
  workflow_dispatch:

jobs:
  call-workflow:
    uses: "./.github/workflows/reusable.yml"
    with:
      who-to-greet: ${ github.actor }
  use-output:
    runs-on: ubuntu-latest
    needs: call-workflow
    steps:
      - name: write output
        run: |
          echo "Current time: ${{ needs.call-workflow.outputs.current-time }}"
    
